# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            POCS
tagline:          'Panoptes Observatory Control System'
description:      'Main system to control Panoptes unit.'
url:              http://http://panoptes.github.io/POCS/

author:
  name:           'Project Panoptes'
  url:            https://www.projectpanoptes.org

relative_permalinks: true

permalink:     date
paginate_path: 'page:num'
paginate:      nil

# Custom vars
version:          0.1.1

github:
  repo:           https://github.com/panoptes/POCS
