# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty

baseurl:		  /POCS

# Setup
title:            POCS
tagline:          'Panoptes Observatory Control System'
description:      'Panoptes Observatory Control System'
url:              http://http://panoptes.github.io/POCS/

author:
  name:           'Project Panoptes'
  url:            https://www.projectpanoptes.org


paginate:         5

# Custom vars
version:          0.1.1

github:
  repo:           https://github.com/panoptes/POCS
